f1=open("abc.txt","w")
f1.write("Hello\n")
f1.write("World\n")
f1.write("welcome\n")
f1.close()
print("file",f1.name,"closed")
f1=open("abc.txt","r")
str=f1.read()
print("read string:",str)
f1.close()
print(f1.name,"is closed")
